# ============================================================
# Broker 3 - Kafka KRaft - Nivel 3 Laboratorio
# ============================================================
node.id=3
process.roles=broker,controller
listeners=PLAINTEXT://0.0.0.0:9094,INTERNAL://0.0.0.0:29094,CONTROLLER://0.0.0.0:19094
advertised.listeners=PLAINTEXT://localhost:9094,INTERNAL://kafka-broker-3:29094
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
inter.broker.listener.name=INTERNAL
controller.listener.names=CONTROLLER
controller.quorum.voters=1@kafka-broker-1:19092,2@kafka-broker-2:19093,3@kafka-broker-3:19094
log.dirs=/var/lib/kafka/data
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
num.partitions=3
log.retention.hours=168
log.segment.bytes=1073741824
